# Generated by Django 4.2.1 on 2023-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='UsersPictures/default.jpg', upload_to='UsersPictures/'),
        ),
    ]
