# Generated by Django 4.2.1 on 2023-05-16 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_rooms', '0002_alter_sharedroom_max_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedroom',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
