# Generated by Django 4.2.1 on 2023-05-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_difficulty_meditation_myuser_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='meditation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.meditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.myuser')),
            ],
        ),
    ]
