# Generated by Django 4.2.1 on 2023-05-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_meditation_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='meditation',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='media',
            name='meditation',
        ),
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='meditation_history',
            name='meditation',
        ),
        migrations.RemoveField(
            model_name='meditation_history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='meditation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='favourite',
        ),
        migrations.DeleteModel(
            name='media',
        ),
        migrations.DeleteModel(
            name='meditation',
        ),
        migrations.DeleteModel(
            name='meditation_history',
        ),
        migrations.DeleteModel(
            name='myuser',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='review',
        ),
        migrations.DeleteModel(
            name='subscription',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
