# Generated by Django 4.2.1 on 2023-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_playlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='picture',
            field=models.ImageField(default='PlaylistPictures/default.jpg', upload_to='PlaylistPictures/'),
        ),
    ]
