# Generated by Django 4.2.1 on 2023-05-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_musiccomment'),
        ('playlist', '0003_playlist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(to='music.music'),
        ),
    ]
