# Generated by Django 4.2.1 on 2023-05-16 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0004_playlist_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='copies',
            field=models.ManyToManyField(related_name='copy_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
